### ISSUE TITLE
Beam energy is assumed to be 10.6 everywhere

### ISSUE THREAD

**Issue by c-dilks** [JeffersonLab/iguana#131]
Look it up via RCDB (or CCDB, if we decide to add the "corrected" beam energy there)

**Comment by dglazier** [comment]
In the first instance you should probably just have a SetBeamEnergy function which propogates to the algorithms (probably in ChangeRun), with the users responsible for calling. Most/all analyses should have a method of getting the beam energy and it should not necessarily be iguana's job.

**Comment by c-dilks** [comment]
> Most/all analyses should have a method of getting the beam energy and it should not necessarily be iguana's job.

The tests will need to know the beam energy, however, or at least assume a default. Perhaps we can restrict Iguana's usage of CCDB and RCDB to the tests, but we may eventually have algorithms that are reliant on CCDB and RCDB.

**Comment by dglazier** [comment]
Perhaps we should do the opposite then and consider if iguana can interface to the dbs as part of its scope. I would be quite happy removing it from clas12root ! And probably it will need database access.
