### ISSUE TITLE
Fiducial cuts for Pass 1

### ISSUE THREAD

**Issue by c-dilks** [JeffersonLab/iguana#151]
Implement a filter algorithm for the original fiducial cuts (the cuts which will use the new distance-to-edge info will be separate)

**Comment by Gregtom3** [comment]
Is this still active? I can get this through.

**Comment by c-dilks** [comment]
I would greatly appreciate the help! I'll email you the version from Stefan that we want to preserve.

**Comment by c-dilks** [comment]
closed by #226.
